### ISSUE TITLE
Great work!! please can i run an image with your model

### ISSUE THREAD

**Issue by sfxnminimah** [arnaldog12/icaonet#2]
I can't seem to find your model, please is it publicly available?

**Comment by sfxnminimah** [comment]
Thanks, seen the script!!

**Comment by sfxnminimah** [comment]
Can't seem to get that tensorflow 1.19.0 version, no other workaround preferably with version 2

**Comment by arnaldog12** [comment]
My model is publicy available. You can download it [here][model]. It only works with TensorFlow v1. Actually, v1.13 or below.


[model]: https://github.com/arnaldog12/icaonet/releases/tag/v0.6.4

**Comment by arnaldog12** [comment]
Hi, @sfxnminimah 
I've just add instructions on README about how to run the ICAONet model.
I hope it helps.

Closing the issue for now, but feel free to reopen it if you need.
