### ISSUE TITLE
Help to test

### ISSUE THREAD

**Issue by YesusPaMa** [arnaldog12/icaonet#3]
I would like to be able to test the model but I don't know what the order of execution of the notebooks is. You will have the step by step to do tests

**Comment by arnaldog12** [comment]
You're right, @YesusPaMa. It's a common request that I receive about this project. I will prepare a notebook with inference code in python and add it on README. I will try do it until end of next week.

**Comment by arnaldog12** [comment]
Hi, @YesusPaMa 
As promised, I've just add instructions on README about how to run the ICAONet model.
I hope it helps.

Closing the issue for now, but feel free to reopen it if you need.
